version: 0.2         
phases:
  install:
    runtime-versions:
      ruby: 2.6
  build:
    commands:
      - g++ server/server.cpp -o fake-redis
artifacts:
  files:
    - 'fake-redis'
  name: fake-redis$(date +%Y-%m-%d)